#!/usr/bin/env python
"""
@package state_manager
@file state_manager
@author Norawit Nangsue
@brief State Manager
        Entry point to the node.
Copyright (C) FIBO
FIBO
"""
from state_manager.state_manager_ros import main

if __name__ == '__main__':
    main()
