#!/usr/bin/env python
"""
@package system_checker
@file system_checker
@author Norawit Nangsue
@brief System Checker
        Entry point to the node.
Copyright (C) FIBO
FIBO
"""
from system_checker.system_checker_ros import main

if __name__ == '__main__':
    main()
