#!/usr/bin/env python
"""
@package acc_lim_vel_filter
@file acc_lim_vel_filter
@author Norawit Nangsue
@brief Acceleration Limit Velocity Filter
        Entry point to the node.
Copyright (C) FIBO
FIBO
"""
from acc_lim_vel_filter.acc_lim_vel_filter_ros import main

if __name__ == '__main__':
    main()
