#!/usr/bin/env python
"""
@package costmap_based_vel_filter
@file costmap_based_vel_filter
@author Norawit Nangsue
@brief Velocity Filter based on provided costmap
        Entry point to the node.
Copyright (C) FIBO
FIBO
"""
from costmap_based_vel_filter.costmap_based_vel_filter_ros import main

if __name__ == '__main__':
    main()
