local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 8.0
  publish_frequency: 4.0
  static_map: false #Complement with Rolling Window
  rolling_window: true
  width: 4.0
  height: 4.0
  resolution: 0.03

  plugins:
  - {name: static_layer,            type: "costmap_2d::StaticLayer"}
  - {name: obstacles_layer_lidar,   type: "costmap_2d::ObstacleLayer"}
  - {name: voxel_layer_camera,      type: "costmap_2d::VoxelLayer"}
  - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}

  obstacles_layer_lidar:
    observation_sources: laser_scan_sensor 
    laser_scan_sensor: {sensor_frame: base_scan, data_type: LaserScan, topic: scan, marking: true, clearing: true}
   
  voxel_layer_camera:
    observation_sources: cloud_marking_sensor cloud_clearing_sensor
    cloud_marking_sensor: {sensor_frame: camera_link, data_type: PointCloud2, topic: /camera/depth/color/points, marking: true, clearing: false, min_obstacle_height: 0.25, obstacle_range: 1.5}
    cloud_clearing_sensor: {sensor_frame: camera_link, data_type: PointCloud2, topic: /camera/depth/color/points, marking: false, clearing: true, min_obstacle_height: -1.0, raytrace_range: 3.0}


  static_layer:
    map_topic: /map_local
    subscribe_to_updates: true
